In [99]:
import pandas as pd
import numpy as np

<h1>Reading CSV File</h1>

In [34]:
Data = pd.read_csv("Student_Adaptiblity.csv")
Data

,Gender,Age,Education Level,Institution Type,IT Student,Location,Load-shedding,Financial Condition,Internet Type,Network Type,Class Duration,Self Lms,Device,Adaptivity Level
0,Boy,21-25,University,Non Government,No,Yes,Low,Mid,Wifi,4G,3-6,No,Tab,Moderate
1,Girl,21-25,University,Non Government,No,Yes,High,Mid,Mobile Data,4G,1-3,Yes,Mobile,Moderate
2,Girl,16-20,College,Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile,Moderate
3,Girl,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,4G,1-3,No,Mobile,Moderate
4,Girl,16-20,School,Non Government,No,Yes,Low,Poor,Mobile Data,3G,0,No,Mobile,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,Girl,16-20,College,Non Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile,Low
1201,Girl,16-20,College,Non Government,No,No,High,Mid,Wifi,4G,3-6,No,Mobile,Moderate
1202,Boy,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,3G,1-3,No,Mobile,Moderate
1203,Girl,16-20,College,Non Government,No,No,Low,Mid,Wifi,4G,1-3,No,Mobile,Low
1204,Girl,11-15,School,Non Government,No,Yes,Low,Poor,Mobile Data,3G,1-3,No,Mobile,Moderate

<h1>Displaying The First 10</h1>

In [35]:
Data.head(10)

,Gender,Age,Education Level,Institution Type,IT Student,Location,Load-shedding,Financial Condition,Internet Type,Network Type,Class Duration,Self Lms,Device,Adaptivity Level
0,Boy,21-25,University,Non Government,No,Yes,Low,Mid,Wifi,4G,3-6,No,Tab,Moderate
1,Girl,21-25,University,Non Government,No,Yes,High,Mid,Mobile Data,4G,1-3,Yes,Mobile,Moderate
2,Girl,16-20,College,Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile,Moderate
3,Girl,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,4G,1-3,No,Mobile,Moderate
4,Girl,16-20,School,Non Government,No,Yes,Low,Poor,Mobile Data,3G,0,No,Mobile,Low
5,Boy,11-15,School,Non Government,No,Yes,Low,Poor,Mobile Data,3G,1-3,No,Mobile,Low
6,Boy,11-15,School,Non Government,No,Yes,Low,Mid,Wifi,4G,0,No,Mobile,Low
7,Boy,11-15,School,Non Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile,Moderate
8,Boy,16-20,College,Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile,Low
9,Boy,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,3G,1-3,No,Mobile,Moderate

<h1>Displaying The Last 10</h1>

In [36]:
Data.tail(10)

,Gender,Age,Education Level,Institution Type,IT Student,Location,Load-shedding,Financial Condition,Internet Type,Network Type,Class Duration,Self Lms,Device,Adaptivity Level
1195,Boy,21-25,University,Non Government,Yes,Yes,High,Poor,Wifi,4G,1-3,Yes,Computer,High
1196,Boy,16-20,College,Government,No,No,High,Mid,Mobile Data,3G,1-3,No,Mobile,Low
1197,Boy,21-25,University,Non Government,Yes,Yes,Low,Mid,Mobile Data,4G,3-6,No,Computer,Moderate
1198,Boy,16-20,College,Government,Yes,No,Low,Mid,Mobile Data,4G,0,No,Mobile,Low
1199,Boy,21-25,University,Non Government,Yes,Yes,Low,Mid,Wifi,4G,3-6,No,Computer,Low
1200,Girl,16-20,College,Non Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile,Low
1201,Girl,16-20,College,Non Government,No,No,High,Mid,Wifi,4G,3-6,No,Mobile,Moderate
1202,Boy,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,3G,1-3,No,Mobile,Moderate
1203,Girl,16-20,College,Non Government,No,No,Low,Mid,Wifi,4G,1-3,No,Mobile,Low
1204,Girl,11-15,School,Non Government,No,Yes,Low,Poor,Mobile Data,3G,1-3,No,Mobile,Moderate

<h1>Display The Column-Names & Data Types</h1>

In [37]:
Data.columns
Data.dtypes

Gender                 str
Age                    str
Education Level        str
Institution Type       str
IT Student             str
Location               str
Load-shedding          str
Financial Condition    str
Internet Type          str
Network Type           str
Class Duration         str
Self Lms               str
Device                 str
Adaptivity Level       str
dtype: object

<h1>Number Of Rows And Colums</h1>

In [38]:
Data.shape    #rows x column

(1205, 14)

<h1>Total Number Of Students</h1>

In [39]:
len(Data)

1205

<h1>Check Is There Any Duplicated Value</h1>

In [40]:
Data.duplicated().sum()

np.int64(949)

<h1>Checking Whether There Is Nan Or Missing Value</h1>

In [41]:
Data.isnull().sum()
Data.isna().sum()

Gender                 0
Age                    0
Education Level        0
Institution Type       0
IT Student             0
Location               0
Load-shedding          0
Financial Condition    0
Internet Type          0
Network Type           0
Class Duration         0
Self Lms               0
Device                 0
Adaptivity Level       0
dtype: int64

<h1>Percentage Missing Values For Each Column
</h1>

In [42]:
for columns in Data.columns:
    print(f"{columns}: {np.unique(Data[columns])}")
    print("*"*30)

Gender: ['Boy' 'Girl']
******************************
Age: ['1-5' '11-15' '16-20' '21-25' '26-30' '6-10']
******************************
Education Level: ['College' 'School' 'University']
******************************
Institution Type: ['Government' 'Non Government']
******************************
IT Student: ['No' 'Yes']
******************************
Location: ['No' 'Yes']
******************************
Load-shedding: ['High' 'Low']
******************************
Financial Condition: ['Mid' 'Poor' 'Rich']
******************************
Internet Type: ['Mobile Data' 'Wifi']
******************************
Network Type: ['2G' '3G' '4G']
******************************
Class Duration: ['0' '1-3' '3-6']
******************************
Self Lms: ['No' 'Yes']
******************************
Device: ['Computer' 'Mobile' 'Tab']
******************************
Adaptivity Level: ['High' 'Low' 'Moderate']
******************************

In [43]:
(Data.isnull().sum()/Data.notnull().sum())*100

Gender                 0.0
Age                    0.0
Education Level        0.0
Institution Type       0.0
IT Student             0.0
Location               0.0
Load-shedding          0.0
Financial Condition    0.0
Internet Type          0.0
Network Type           0.0
Class Duration         0.0
Self Lms               0.0
Device                 0.0
Adaptivity Level       0.0
dtype: float64

<h1>Calculate Frequency And Percentage Distributions For Diffrent Columns</h1>

In [100]:
for col in Data.columns:
    category_count = Data[col].value_counts()
    per_cat_count = ((category_count/len(Data[col]))*100)
    result = pd.DataFrame({
        "Frequency": category_count,
        "Percentage": per_cat_count.round(2)
    })
    print(result)

        Frequency  Percentage
Gender
Boy           663       55.02
Girl          542       44.98
       Frequency  Percentage
Age
21-25        374       31.04
11-15        353       29.29
16-20        278       23.07
1-5           81        6.72
26-30         68        5.64
6-10          51        4.23
                 Frequency  Percentage
Education Level
School                 530       43.98
University             456       37.84
College                219       18.17
                  Frequency  Percentage
Institution Type
Non Government          823        68.3
Government              382        31.7
            Frequency  Percentage
IT Student
No                901       74.77
Yes               304       25.23
          Frequency  Percentage
Location
Yes             935       77.59
No              270       22.41
               Frequency  Percentage
Load-shedding
Low                 1004       83.32
High                 201       16.68
                     Frequency  Percentage
Financial Condition
Mid                        878       72.86
Poor                       242       20.08
Rich                        85        7.05
               Frequency  Percentage
Internet Type
Mobile Data          695       57.68
Wifi                 510       42.32
              Frequency  Percentage
Network Type
4G                  775       64.32
3G                  411       34.11
2G                   19        1.58
                Frequency  Percentage
Class Duration
1-3                   840       69.71
3-6                   211       17.51
0                     154       12.78
          Frequency  Percentage
Self Lms
No              995       82.57
Yes             210       17.43
          Frequency  Percentage
Device
Mobile         1013       84.07
Computer        162       13.44
Tab              30        2.49
                  Frequency  Percentage
Adaptivity Level
Moderate                625       51.87
Low                     480       39.83
High                    100        8.30

<h1>Calculate The Number Of Students In Each Adaptability Category</h1>

In [98]:
adpt_level_count = Data["Adaptivity Level"].value_counts()
for lvl in adpt_level_count.iloc[0:]:
    print(adpt_level_count[lvl],":",lvl/len(Data["Adaptivity Level"])*100)

KeyError: 625